In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("abalone.csv")
df

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [3]:
df.isnull().sum()

Sex                0
Length             0
Diameter           0
Height             0
Whole weight       0
Shucked weight     0
Viscera weight     0
Shell weight       0
Rings              0
dtype: int64

In [4]:
df.dtypes

Sex                 object
Length             float64
Diameter           float64
Height             float64
Whole weight       float64
Shucked weight     float64
Viscera weight     float64
Shell weight       float64
Rings                int64
dtype: object

In [5]:
df['Sex']=df['Sex'].astype('category').cat.codes
df.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [6]:
X = df.iloc[0:,1:]
y = df['Sex']
X.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [7]:
X.describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [8]:
set(y)

{0, 1, 2}

In [9]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(X)
X_transform=ss.transform(X)

In [10]:
pd.DataFrame(X_transform,columns=X.columns)
pd.DataFrame(X_transform,columns=X.columns).describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
count,4.177000e+03,4.177000e+03,4.177000e+03,4.177000e+03,4.177000e+03,4.177000e+03,4.177000e+03,4.177000e+03
mean,-5.834718e-16,-3.027929e-16,3.912493e-16,9.185853e-17,-1.020650e-17,2.704723e-16,2.976897e-16,8.505419e-17
std,1.000120e+00,1.000120e+00,1.000120e+00,1.000120e+00,1.000120e+00,1.000120e+00,1.000120e+00,1.000120e+00
min,-3.739154e+00,-3.556267e+00,-3.335953e+00,-1.686092e+00,-1.614731e+00,-1.643173e+00,-1.705134e+00,-2.771180e+00
25%,-6.161975e-01,-5.833158e-01,-5.862075e-01,-7.897577e-01,-7.811585e-01,-7.946415e-01,-7.819095e-01,-5.998184e-01
50%,1.749513e-01,1.725193e-01,1.156329e-02,-5.963767e-02,-1.052891e-01,-8.753202e-02,-3.470794e-02,-2.896238e-01
75%,7.579031e-01,7.267984e-01,6.093341e-01,6.613049e-01,6.426730e-01,6.606355e-01,6.478319e-01,3.307653e-01
max,2.423480e+00,2.440025e+00,2.368329e+01,4.072271e+00,5.085388e+00,5.286500e+00,5.504642e+00,5.914268e+00

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X_transform,y,random_state=42,test_size=0.2)

In [12]:
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [13]:
y_pred=log.predict(X_test)
y_pred

array([0, 0, 0, 2, 2, 1, 1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 0, 2,
       2, 0, 2, 1, 1, 1, 2, 2, 2, 0, 1, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 1,
       0, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 1, 1, 2, 0, 0, 1, 1, 2,
       1, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1,
       2, 2, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 2, 2, 2, 1, 2, 1, 2, 2,
       2, 1, 0, 2, 1, 1, 1, 2, 2, 0, 0, 2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 1,
       2, 1, 1, 1, 0, 0, 1, 2, 1, 2, 1, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0,
       2, 2, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0, 1, 1, 2,
       1, 1, 2, 0, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 2, 2, 0, 2,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 2, 1, 2, 2, 1, 2, 0, 2, 1, 2, 0,
       2, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 1, 2, 1, 1, 1, 2, 2, 0,
       2, 1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 1, 0, 0, 0, 2, 1, 0, 1, 2, 2, 1, 0,
       0, 1, 2, 0, 2, 1, 2, 1, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2,
       1, 1, 2, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 2,
       1, 1, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 0, 2,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0, 2, 1, 1, 2, 2, 1, 0, 1, 2,
       2, 0, 2, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 2,
       1, 2, 2, 1, 2, 2, 2, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0,
       2, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 1, 2, 2, 2, 1, 2,
       1, 1, 0, 2, 2, 1, 0, 2, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 1, 2, 1, 1,
       1, 2, 0, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 0, 2, 1, 0, 2, 1, 1, 2, 0,
       2, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2,
       1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 1, 0, 0, 2, 2, 1,
       1, 2, 1, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 1, 0, 1, 1,
       2, 2, 1, 1, 2, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 2,
       1, 2, 1, 1, 1, 0, 0, 1, 2, 2, 0, 0, 2, 1, 1, 2, 0, 2, 1, 1, 0, 0,
       2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 0, 1, 0, 2, 2, 0, 2,
       1, 1, 2, 2, 0, 0, 1, 1, 2, 0, 1, 2, 0, 2, 0, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 2, 1, 0, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 0,
       0, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2,
       2, 0, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 1, 0, 1, 0, 2, 2, 1, 0, 1, 1,
       2, 1, 2, 1, 2, 2, 1, 1, 2, 0, 0, 2, 0, 1, 0, 2, 0, 1, 1, 2, 1, 1,
       0, 0, 2, 2, 2, 0, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 0, 1,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1],
      dtype=int8)

In [14]:
y_test

866     2
1483    2
599     0
1702    0
670     2
       ..
3093    0
1651    0
2897    1
3953    1
1830    1
Name: Sex, Length: 836, dtype: int8

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.583732057416268

In [16]:
y_proba=log.predict_proba(X_test)
y_proba

array([[0.52186175, 0.0528136 , 0.42532466],
       [0.36200939, 0.27745963, 0.36053099],
       [0.57091526, 0.02147295, 0.40761179],
       ...,
       [0.33779232, 0.27738625, 0.38482143],
       [0.1540447 , 0.57472466, 0.27123064],
       [0.05911323, 0.80631669, 0.13457008]])